name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Verify Node.js and npm versions
      run: |
        echo "Using Node.js $(node --version)"
        echo "Using npm $(npm --version)"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci --no-audit
        else
          npm install
          git add package-lock.json
        fi

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test
      env:
        CI: true